In [38]:
!pip install numpy

In [22]:
# Importing the numpy library
import numpy as np

In [23]:
# Defining a list containing integers
lst = [1,2,3]

In [24]:
# Checking the type of the list
type(lst)

list

In [25]:
# Converting the list to a numpy array
arr = np.array(lst)

In [8]:
arr

array([1, 2, 3])

In [26]:
# Checking the type of the numpy array
type(arr)

numpy.ndarray

In [27]:
# Checking the dimensionality of the numpy array
arr.ndim

1

In [28]:
# Creating a 2D list
lst = [[1,2,3],
       [1,2,3],
       [1,2,3]]

In [29]:
# Converting the 2D list to a numpy array
arr = np.array(lst)

In [31]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [32]:
# Checking the dimensionality of the numpy array
arr.ndim

2

In [33]:
# Checking the shape of the numpy array
arr.shape

(3, 3)

In [34]:
# Checking the number of elements in the numpy array
arr.size

9

In [35]:
# Checking the data type of the numpy array
arr.dtype

dtype('int32')

In [36]:
# Creating a numpy array filled with zeros
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
# Creating a numpy array filled with ones
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])