In [1]:
import numpy as np

In [3]:
# generate random number (0-1)
np.random.random()

0.9397890234533359

In [5]:
np.random.random((3,3))

array([[0.71853656, 0.25667356, 0.25442974],
       [0.48610591, 0.04848435, 0.10171763],
       [0.61677654, 0.8308914 , 0.83549214]])

In [6]:
np.random.random((3,3))

array([[0.89176241, 0.69054811, 0.72146647],
       [0.95843541, 0.9940384 , 0.6594025 ],
       [0.25281261, 0.84476692, 0.21315271]])

In [7]:
# generate number in a particular sequence
# arange,linspace
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
#give 20 number from 1-10 with equal distance
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
arr = np.random.random((4,3))

In [15]:
arr

array([[0.76618753, 0.92265465, 0.67586726],
       [0.71022529, 0.89293456, 0.12336598],
       [0.91402489, 0.37749808, 0.29489043],
       [0.63228485, 0.97671303, 0.52427631]])

In [17]:
arr = np.reshape(arr,(3,4))

In [18]:
arr

array([[0.76618753, 0.92265465, 0.67586726, 0.71022529],
       [0.89293456, 0.12336598, 0.91402489, 0.37749808],
       [0.29489043, 0.63228485, 0.97671303, 0.52427631]])

In [19]:
arr = np.reshape(arr,(6,2))
arr

array([[0.76618753, 0.92265465],
       [0.67586726, 0.71022529],
       [0.89293456, 0.12336598],
       [0.91402489, 0.37749808],
       [0.29489043, 0.63228485],
       [0.97671303, 0.52427631]])

In [20]:
# converting arr into 1-D
arr.flatten()

array([0.76618753, 0.92265465, 0.67586726, 0.71022529, 0.89293456,
       0.12336598, 0.91402489, 0.37749808, 0.29489043, 0.63228485,
       0.97671303, 0.52427631])