In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
arr + 1

array([2, 3, 4, 5, 6, 7])

In [5]:
arr - 1

array([0, 1, 2, 3, 4, 5])

In [6]:
arr * 2

array([ 2,  4,  6,  8, 10, 12])

In [7]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [8]:
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
arr.max()

6

In [10]:
arr.min()

1

In [11]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr.max(axis=0) #max elemnt col-wise

array([7, 8, 9])

In [14]:
arr.max(axis=1) #max elemnt row-wise

9

In [15]:
arr.min(axis=0)

array([1, 2, 3])

In [16]:
arr.sum()

45